[project]
name = "CCD-Plugin"
version = "25.8"
description = "Qgis plugin for Continuous Change Detection (CCDC) algorithm of a time series at a given coordinate"
authors = [
    { name = "Xavier Corredor Llano, SMByC", email = "xavier.corredor.llano@gmail.com" },
]
license = { text = "GPL-2.0-or-later" }
requires-python = ">=3.9"
dependencies = [
    "plotly",
]

[project.urls]
Homepage = "https://github.com/SMByC/CCD-Plugin"
Repository = "https://github.com/SMByC/CCD-Plugin"
Issues = "https://github.com/SMByC/CCD-Plugin/issues"

[project.optional-dependencies]
dev = [
    "ruff",
]

[dependency-groups]
dev = [
    "ruff",
]

[tool.pyright]
extraPaths = [".."]  # include project folder
venv = ".venv"

[tool.ruff]
line-length = 120
extend-exclude = ["extlibs", "resources.py"]

[tool.ruff.lint]
preview = true
explicit-preview-rules = true
select = ["E", "W", "F"]
extend-select = ["E226"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
