# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: package-plugin

on: workflow_dispatch

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install paver
    - name: Package QGIS Plugin
      run: |
        paver setup
        paver package_extlibs
#        paver package

#    - name: Upload artifact full-plugin by OS
#      uses: actions/upload-artifact@v3
#      with:
#        name: CCD_Plugin_${{ matrix.os }}
#        path: ./CCD_Plugin_*.zip

    - name: Upload artifact extlibs by OS
      uses: actions/upload-artifact@v3
      with:
        name: extlibs_${{ matrix.os }}_py${{ matrix.python-version }}
        path: ./extlibs_*_py${{ matrix.python-version }}.zip

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        
        
